accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth', include('accounts.urls', namespace='accounts')),
    path('', include('webapp.urls', 'webapp')),
]

webapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from webapp.views import OrderListView, OrderDetailView, OrderCreateView, OrderUpdateView, OrderRejectView, FoodListView, FoodDetailView, FoodCreateView, FoodUpdateView, OrderFoodCreateView, OrderFoodUpdateView, OrderDeliverView, OrderFoodDeleteView


app_name = 'webapp'


urlpatterns = [
    path('', OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('order/create', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/reject', OrderRejectView.as_view(), name='order_cancel'),
    path('order/<int:pk>/status/deliver', OrderDeliverView.as_view(), name='order_deliver'),
    path('order/<int:pk>/update', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/food/create', OrderFoodCreateView.as_view(), name='order_food_create'),
    path('order/food/<int:pk>/update', OrderFoodUpdateView.as_view(), name='order_food_update'),
    path('order/<int:pk>/food/delete', OrderFoodDeleteView.as_view(), name='order_food_delete'),
    path('foods', FoodListView.as_view(), name='food_list'),
    path('foods/<int:pk>', FoodDetailView.as_view(), name='food_detail'),
    path('foods/create', FoodCreateView.as_view(), name='food_create'),
    path('foods/<int:pk>/update', FoodUpdateView.as_view(), name='food_update')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='employee', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, verbose_name='Телефон')

    def __str__(self):
        return self.user.get_full_name()


class Food(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')
    photo = models.ImageField(verbose_name='Фотография')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_PREPARING = 'preparing'
    STATUS_ON_WAY = 'on_way'
    STATUS_DELIVERED = 'delivered'
    STATUS_CANCELED = 'canceled'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый'),
        (STATUS_PREPARING, 'Готовится'),
        (STATUS_ON_WAY, 'В пути'),
        (STATUS_DELIVERED, 'Доставлен'),
        (STATUS_CANCELED, 'Отменён')
    )

    contact_phone = models.CharField(max_length=50, verbose_name='Контактный телефон')
    contact_name = models.CharField(max_length=100, verbose_name='Имя клиента')
    delivery_address = models.CharField(max_length=200, null=True, blank=True, verbose_name='Адрес доставки')
    status = models.CharField(max_length=20, default=STATUS_NEW, verbose_name='Статус', choices=STATUS_CHOICES)
    operator = models.ForeignKey(User, null=True, blank=True, related_name='orders', verbose_name='Оператор', on_delete=models.PROTECT)
    courier = models.ForeignKey(User, null=True, blank=True, related_name='delivered', verbose_name='Курьер', on_delete=models.PROTECT)

    def __str__(self):
        return self.contact_name


class OrderFood(models.Model):
    order = models.ForeignKey(Order, related_name='foods', verbose_name='Заказ', on_delete=models.PROTECT)
    food = models.ForeignKey(Food, related_name='+', verbose_name='Блюдо', on_delete=models.PROTECT)
    amount = models.IntegerField(verbose_name='Количество')

    def __str__(self):
        return str(self.food)

webapp/forms.py
from django import forms
from webapp.models import Food, OrderFood

class OrderFoodForm(forms.ModelForm):
    class Meta:
        model = OrderFood
        exclude = ['order']


class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        exclude = []


class OrderForm(forms.ModelForm):
    class Meta:
        model = OrderFood
        exclude = []

webapp/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View, FormView
from django.http import HttpResponseRedirect, JsonResponse
from webapp.models import Order, Food, OrderFood
from webapp.forms import OrderFoodForm, FoodForm, OrderForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.

class OrderListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Order
    template_name = 'order_list.html'
    permission_required = 'webapp.view_order'


class OrderDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView, FormView):
    model = Order
    template_name = 'order_detail.html'
    permission_required = 'webapp.view_order'
    form_class = OrderFoodForm


class OrderCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'order_create.html'
    permission_required = 'webapp.add_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.operator = self.request.user
        return super().form_valid(form)



class OrderUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Order
    form_class = OrderForm
    template_name = 'order_update.html'
    permission_required = 'webapp.change_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.order = get_object_or_404(Order, pk=self.kwargs['pk'])
        return super().form_valid(form)



class OrderRejectView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Order
    template_name = 'order_cancel.html'
    permission_required = 'webapp.delete_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.status = 'canceled'
        self.object.save()
        return HttpResponseRedirect(success_url)



class OrderDeliverView(PermissionRequiredMixin, View):
    permission_required = 'webapp.deliver_order'

    def get(self, *args, **kwargs):
        object = get_object_or_404(Order, pk=kwargs['pk'])
        success_url = reverse('webapp:order_detail', kwargs={'pk': object.pk})
        if object.status == 'preparing':
            object.status = 'on way'
            object.courier = self.request.user
            object.save()
        elif object.status == 'on way':
            if object.courier == self.request.user:
                object.status = 'delivered'
                object.save()
        return HttpResponseRedirect(success_url)




class OrderFoodCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = OrderFood
    form_class = OrderFoodForm
    permission_required = 'webapp.add_orderfood'

    def form_valid(self, form):
        order = get_object_or_404(Order, pk=self.kwargs.get('pk'))
        form.instance.order = order
        order_food = form.save()
        return JsonResponse({
            'food_name': order_food.food.name,
            'food_pk': order_food.food.pk,
            'amount': order_food.amount,
            'pk': order_food.pk,
            'edit_url': reverse('webapp:order_food_update', kwargs={'pk': order_food.pk})
        })

    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors
        }, status='422')

class OrderFoodUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = OrderFood
    form_class = OrderFoodForm
    permission_required = 'webapp.add_orderfood'


    def form_valid(self, form):
        order_food = form.save()
        return JsonResponse({
            'food_name': order_food.food.name,
            'food_pk': order_food.food.pk,
            'amount': order_food.amount,
            'pk': order_food.pk
        })


    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors
        }, status='422')




class OrderFoodDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = OrderFood
    form_class = OrderFoodForm
    template_name = 'order_food_delete.html'
    permission_required = 'webapp.delete_orderfood'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})



class FoodListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Food
    template_name = 'food_list.html'
    permission_required = 'webapp.view_food'


class FoodDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Food
    template_name = 'food_detail.html'
    permission_required = 'webapp.view_food'





class FoodCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Food
    form_class = FoodForm
    template_name = 'food_create.html'
    permission_required = 'webapp.add_food'


    def get_success_url(self):
        return reverse('webapp:food_detail', kwargs={'pk': self.object.pk})




class FoodUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Food
    form_class = FoodForm
    template_name = 'food_update.html'
    permission_required = 'webapp.change_food'

    def get_success_url(self):
        return reverse('webapp:food_detail', kwargs={'pk': self.object.pk})

webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
                <li class="nav-item navbar-text">Привет, {{ request.user.username }}!</li>
                <li class="nav-item">
                    <a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'webapp:order_list' %}" class="nav-link">На главную</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'webapp:food_list' %}">Список блюд</a>
                </li>
                 {% block menu %}{% endblock %}
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'accounts:login' %}" class="nav-link">Вход</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

webapp/templates/food_create.html
{% extends 'base.html' %}
{% block title %}Добавить еду{% endblock %}
{% block menu %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:order_create' %}">Заказать</a>
        </li>
{% endblock %}
{% block content %}
    <h1>Еда</h1>
    <form action="{% url 'webapp:food_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary ml-3">Сохранить</button>
    </form>
{% endblock %}

webapp/templates/food_detail.html
{% extends 'base.html' %}
{% block title %}Статья{% endblock %}
{% block menu %}
        {% if perms.webapp.add_food %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:food_create' %}">Добавить еду</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:food_update' food.pk %}">Редактировать еду</a>
            </li>

        {% endif %}
{% endblock %}
{% block content %}
    <div>
        <h1 class="text-center mt-4 mb-3">{{ food.name }}</h1> <h4 class="text-right"> Цена: {{ food.price }} </h4>
            <p class="mb-3">{{ food.description }}</p>
            <p><a href="{% url 'webapp:order_food_delete' food.pk %}">Удалить еду</a></p>
            <img src="{{ food.photo.url }}" alt="Картинка еды">
    </div>


{% endblock %}

webapp/templates/food_list.html
{% extends 'base.html' %}
{% block title %}Меню{% endblock %}
{% block menu %}
        {% if perms.webapp.add_order %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:order_create' %}">Заполнять данные для заказа</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:food_create' %}">Добавить еду</a>
            </li>
        {% endif %}

{% endblock %}
{% block content %}
        {% for food in food_list %}
            <div class="mb-4 mt-4">
            <a href="{% url 'webapp:food_detail' food.pk %}">
                    <h4>{{ food.name }}</h4>
            </a>
            </div>
        {% endfor %}
{% endblock %}

webapp/templates/food_update.html
{% extends 'base.html' %}
{% block title %}Еда{% endblock %}
{% block menu %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:order_create' %}">Заказать</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:food_create' %}">Добавить еду</a>
        </li>
{% endblock %}
{% block content %}

<h1>Редактирование еды</h1>
    <form action="{% url 'webapp:food_update' form.instance.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary ml-3">Сохранить</button>
    </form>

{% endblock %}

webapp/templates/order_cancel.html
{% extends 'base.html' %}
{% block title %}Отменить заказ{% endblock %}
{% block menu %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:order_create' %}">Заполнять данные для заказа</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:order_food_create' order.pk%}">Выбрать еду</a>
        </li>
{% endblock %}
{% block content %}
        <h1>Отменение заказа</h1>
        {% if order.status == 'delivered' or order.status == 'on way' or order.status == 'canceled' %}
            <h2>Заказ уже доставляется, доставлен или уже отменен!</h2>
        {% else %}
            <h5>Вы уверены, что хотите отменить заказ   {% for order_food in order.foods.all %}
                                                    {{ order_food.food.name }}
                                                {% endfor %}?</h5>
            <form action="{% url 'webapp:order_cancel' order.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn, btn-primary">Отменить</button>
            </form>
        {% endif %}
{% endblock %}

webapp/templates/order_create.html
{% extends 'base.html' %}
{% block title %}Заказать{% endblock %}
{% block content %}
    <h1>Заказ</h1>
    <form action="{% url 'webapp:order_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary ml-3">Сохранить</button>
    </form>
{% endblock %}

webapp/templates/order_detail.html
{% extends 'base.html' %}
{% block title %}Заказы{% endblock %}
{% block menu %}
        {% if perms.webapp.add_order %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:order_create' %}">Заполнять данные для заказа</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:order_food_create' order.pk %}" id="order_food_add_link">Выбрать еду</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:order_update' order.pk %}">Редактировать данные для заказа</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:order_cancel' order.pk %}">Отменить заказ</a>
            </li>
        {% endif %}
        {% if perms.webapp.deliver_order %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:order_deliver' order.pk %}">Получить заказ</a>
            </li>
        {% endif %}
{% endblock %}
{% block content %}
    <div>
        <h1 class="text-center mt-4 mb-3">Заказ</h1>
            <h4 class="mb-5">Данные заказчика: {{ order.contact_name }}, {{ order.contact_phone }}, {{ order.delivery_address }}</h4>
            <ul class="ml-5" id="order_food_list">
                {% for order_food in order.foods.all %}
                    <li id="order_food_{{ order_food.pk }}">
                        <span id="order_food_name_{{ order_food.pk }}" data-food_pk="{{ order_food.food.pk }}">{{ order_food.food.name }}</span>:
                        <span id="order_food_amount_{{ order_food.pk }}">{{ order_food.amount }}</span> шт.
                        {% if perms.webapp.change_orderfood %} <br>
                            <a class="edit_link" href="{% url 'webapp:order_food_update' order_food.pk %}" data-pk="{{ order_food.pk }}">Изменить</a> <br>
                            <a href="{% url 'webapp:order_food_delete' order_food.pk %}">Удалить</a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            <div class="text-right">
                <h6>Курьер: {{ order.courier.first_name }}</h6>
                <h6>Оператор: {{ order.operator.first_name }}</h6>
                <h4 class="mr-3">Статус: {{ order.get_status_display }}</h4>
            </div>
    </div>


    <div class="modal" tabindex="-1" role="dialog" id="food_edit_modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Добавить блюда</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <form id="food_form" action="{% url 'webapp:order_food_create' order.pk %}" method="post">
                  <div class="form-group">
                      <div class="text-danger" id="food_form_errors"></div>
                      {% csrf_token %}
                      {{ form.as_p }}
                  </div>
              </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="food_submit">Добавить</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          </div>
        </div>
      </div>
    </div>

{% endblock %}
{% block scripts %}
    <script type="application/javascript">
        function onCreateSuccess(response, status) {
            // выводим содержимое ответа и статус в консоль.
            console.log(response);
            console.log(status);

            // создаём новый пункт списка блюд
            let newFoodLi = $('<li></li>');

            let foodNameSpan = $('<span></span>')
                .attr('id', 'order_food_name_' + response.pk)
                .data('food_pk', response.food_pk)
                .text(response.food_name);
            let foodAmountSpan = $('<span></span>')
                .attr('id', 'order_food_amount_' + response.pk)
                .text(response.amount);
            let editLink = $('<a></a>')
                .addClass('edit_link')
                .attr('href', response.edit_url)
                .data('pk', response.pk)
                .text('Изменить')
                .click(onOrderFoodUpdate);
            let deleteLink = $('<a></a>')
                .attr('href', '#')
                .text('Удалить');

            newFoodLi
                .attr('id', 'order_food_' + response.pk)
                .append(foodNameSpan)
                .append(': ')
                .append(foodAmountSpan)
                .append(' шт. (')
                .append(editLink)
                .append(' / ')
                .append(deleteLink)
                .append(')');

            // добавляем новый пункт в список
            $('#order_food_list').append(newFoodLi);

            // выключаем модальное окно
            $('#food_edit_modal').modal('hide');
        }


        // функция, которая обрабатывает успешный AJAX-запрос на изменение блюда
        function onUpdateSuccess(response, status) {
            // выводим содержимое ответа и статус в консоль.
            console.log(response);
            console.log(status);

            // находим нужное блюдо на странице и меняем его данные на новые, пришедшие в ответе
            let pk = response['pk'];
            let food_name_span = $('#order_food_name_' + pk);
            food_name_span.text(response.food_name);
            food_name_span.data('food_pk', response.food_pk);
            $('#order_food_amount_' + pk).text(response.amount);

            // прячем модалку
            $('#food_edit_modal').modal('hide');
        }


        // функция, которая обрабатывает неуспешный AJAX-запрос
        // и на добавление, и на изменение блюда
        function onFormSubmitError(response, status) {
            // выводим содержимое ответа и статус в консоль.
            console.log(response);
            console.log(status);

            // если ответ содержит ключ errors,
            // выводим его содержимое в специальный div в модалке
            if (response.errors) {
                $('#food_form_errors').text(response.errors.toString());
            }
        }


        // функция, которая отправляет AJAX-запрос с формой
        // и вызывает переданную функцию в случае успеха
        function orderFoodFormSubmit(success) {
            // определяем url для отправки формы food_form по её свойству action:
            let url = $('#food_form').attr('action');

            // собираем данные, указанные в форме food_form
            let data = {
                food: $('#id_food').val(),
                amount: $('#id_amount').val(),
                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
            };

            // отправляем данные
            // опции success и error должны быть функциями,
            // которые jQuery вызовет при успешной и неуспешной отправке запроса, соответственно
            // (т.н. "колбэки" - "callback" - функции обратной связи).
            $.ajax({
                url: url,
                method: 'POST',
                data: data,
                success: success,
                error: onFormSubmitError
            });
        }


        // Обработка клика по ссылке "Добавить"
        function onOrderFoodCreate(event) {
            event.preventDefault();

            // меняем заголовок и текст на кнопке "Добавить" в модалке
            $("#food_edit_modal .modal-title").text('Добавить блюдо');
            $("#food_submit").text('Добавить');

            // меняем action в форме в модалке на url,
            // указанный в href нажатой ссылки на добавление.
            // this в обработчиках событий указывает на тот объект,
            // к которому привязано событие, в данному случае -
            // на ту ссылку, которая была нажата.
            let foodForm = $('#food_form');
            foodForm.attr('action', $(this).attr('href'));

            // сбрасываем данные в форме редактирования блюда в модалке на пустые значения
            $('#id_food').val('');
            $('#id_amount').val('');

            // отключаем предыдущие обработчики события отправки формы
            foodForm.off('submit');

            // назначаем действие на отправку формы food_form.
            foodForm.on('submit', function (e) {
                // отменить обычную отправку формы (действие по умолчанию с перезагрузкой страницы)
                e.preventDefault();

                // отправить форму с помощью функции orderFoodFormSubmit, которая использует AJAX-запрос.
                // в случае успеха вызвать функцию onCreateSuccess
                orderFoodFormSubmit(onCreateSuccess);
            });

            // показываем модалку на экране
            $('#food_edit_modal').modal('show');
        }


        // Обработка клика по ссылке "Изменить"
        function onOrderFoodUpdate(event) {
            // отменяем действие по умолчанию (переход по ссылке)
            event.preventDefault();

            // меняем заголовок и текст на кнопке "Добавить" в модалке
            $("#food_edit_modal .modal-title").text('Изменить блюдо');
            $("#food_submit").text('Изменить');

            // меняем action в форме в модалке на url,
            // указанный в href нажатой ссылки на редактирование.
            // this в обработчиках событий указывает на тот объект,
            // к которому привязано событие, в данном случае -
            // на ту ссылку, которая была нажата.
            let foodForm = $('#food_form');
            foodForm.attr('action', $(this).attr('href'));

            // находим элементы с именем блюда и количеством блюда на странице,
            // используя свойство data-pk нажатой ссылки.
            let foodPk = $(this).data('pk');
            let foodName = $('#order_food_name_' + foodPk);  // '#order_food_name_1'
            let foodAmount = $('#order_food_amount_' + foodPk);  // '#order_food_amount_1'

            // задаём в форме исходные значения для данного блюда в заказе.
            // т.к. на странице выводится название блюда, а нам нужен его pk,
            // pk сохраняем и получаем через data-атрибут food_pk.
            $('#id_food').val(foodName.data('food_pk'));
            $('#id_amount').val(foodAmount.text());

            // отключаем предыдущие обработчики события отправки формы
            foodForm.off('submit');

            // задаём обработчик события отправки формы
            foodForm.submit(function (event) {
                // отменяем действие по умолчанию (обычная отправка формы)
                event.preventDefault();

                // отправить форму с помощью функции orderFoodFormSubmit, которая использует AJAX-запрос.
                // в случае успеха вызвать функцию onUpdateSuccess
                orderFoodFormSubmit(onUpdateSuccess);
            });

            // показываем модалку на экране.
            $('#food_edit_modal').modal('show');
        }


        // настраиваем создание и изменение блюд
        // через AJAX после загрузки страницы.
        window.addEventListener('load', function () {
            // назначаем действие на нажатие кнопки "Добавить" в модалке.
            // кнопка не находится внутри формы, поэтому её требуется настроить здесь.
            $('#food_submit').on('click', function (e) {
                // отправляем форму
                $('#food_form').submit();
            });

            // настраиваем создание блюд по клику на ссылку "Добавить"
            $("#order_food_add_link").click(onOrderFoodCreate);

            // настраиваем изменение блюд по клику на ссылки "Изменить"
            $('#order_food_list .edit_link').click(onOrderFoodUpdate);
        });
    </script>
{% endblock %}

webapp/templates/order_food_create.html
{% extends 'base.html' %}
{% block title %}Заказать{% endblock %}
{% block content %}
    <h1>Заказ</h1>
        <form action="{% url 'webapp:order_food_create' order.pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary ml-3">Сохранить</button>
        </form>
{% endblock %}

webapp/templates/order_list.html
{% extends 'base.html' %}
{% block title %}Статьи{% endblock %}
{% block menu %}
        {% if perms.webapp.add_order %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:order_create' %}">Заполнять данные для заказа</a>
            </li>
        {% endif %}
{% endblock %}
{% block content %}
        {% for order in order_list %}
            <div class="mb-4 mt-4">
            <a href="{% url 'webapp:order_detail' order.pk %}">
                {% for order_food in order.foods.all %}
                    <h4>{{ order_food.food.name }}</h4>
                {% endfor %}
                <h6>Заказчик: {{ order.contact_name }}</h6>
                <h6>Статус: {{ order.get_status_display }}</h6>
            </a>
            </div>
        {% endfor %}
{% endblock %}